// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAnB1uPEDt2qr7pGTyInh6JkWUVNVwTKo',
    appId: '1:638186012464:android:f0d8ba4ac3554dd912d2f5',
    messagingSenderId: '638186012464',
    projectId: 'chatapp-9f988',
    storageBucket: 'chatapp-9f988.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYBFzzsQmoDztKW4jq-hU800Ru2gk8CJk',
    appId: '1:638186012464:web:51cfc02b97e78a6912d2f5',
    messagingSenderId: '638186012464',
    projectId: 'chatapp-9f988',
    authDomain: 'chatapp-9f988.firebaseapp.com',
    storageBucket: 'chatapp-9f988.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0p-shT7zDs6eXTfSGBYWQ4ykTdQvcUVo',
    appId: '1:638186012464:ios:2e4e1d6230d4098212d2f5',
    messagingSenderId: '638186012464',
    projectId: 'chatapp-9f988',
    storageBucket: 'chatapp-9f988.firebasestorage.app',
    iosBundleId: 'com.example.chatProject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0p-shT7zDs6eXTfSGBYWQ4ykTdQvcUVo',
    appId: '1:638186012464:ios:2e4e1d6230d4098212d2f5',
    messagingSenderId: '638186012464',
    projectId: 'chatapp-9f988',
    storageBucket: 'chatapp-9f988.firebasestorage.app',
    iosBundleId: 'com.example.chatProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYBFzzsQmoDztKW4jq-hU800Ru2gk8CJk',
    appId: '1:638186012464:web:b73712f6d686c42312d2f5',
    messagingSenderId: '638186012464',
    projectId: 'chatapp-9f988',
    authDomain: 'chatapp-9f988.firebaseapp.com',
    storageBucket: 'chatapp-9f988.firebasestorage.app',
  );

}